<?php
    return array(
		// GENERAL PHRASES
        'bluelte_theme_settings'        => 'BlueLTE Theme',
        'general'                     => 'General',
        'options_reset'               => 'BlueLTE theme settings reset to default',
        'options_saved'               => 'BlueLTE theme settings saved',
        'hide_this_banner'            => 'Hide this banner',
        'facebook'                    => 'Facebook',
        'twitter'                     => 'Twitter',
        'email'                       => 'Email',
        'pinterest'                   => 'Pinterest',
        'google-plus'                 => 'Google Plus',
        'vk'                          => 'Vk',
        'follow_us_on_x'              => 'Follow us on ^',
        'send_us_an_email'            => 'Send us an email',
        'bluelte_theme'                 => 'BlueLTE Theme',
        'bluelte_discussion_forum'      => 'BlueLTE discussion forum',
        'search_answers'              => 'Search answers for all your queries',
        'one_destination'             => 'One destination for all your queries',
        'get_expert_answers'          => 'Get answers from the experts',
        'responsive_q2a_theme'        => 'Awesome q2a theme',
        'ask_us_anything'             => 'Ask us anything',
        'page_not_found_default_text' => 'Oops.. Page not found',
        'admin_notes'                 => 'Please visit to the `Admin/BlueLTE theme settings` section for customizing the bluelte theme . Here only you can only reset the bluelte theme settings to its defaults',
        'ask_placeholder'             => 'Type your question',
        'ask_button'                  => 'Ask !',
		
		// OPTIONS PHRASES
		'bluelte_activate_prod_mode'           => 'Activate Prod Mode (use minified css, js and Bootstrap CDN)',
        'bluelte_enable_top_bar'               => 'Enable top bar (above the main navigation)',
        'bluelte_top_bar_left_text'            => 'Top bar left text',
        'bluelte_top_bar_right_text'           => 'Top bar right text',
        'bluelte_show_top_social_icons'        => 'Show social icons at top',
        'bluelte_enable_sticky_header'         => 'Enable sticky header on scroll',
        'bluelte_enable_back_to_top_btn'       => 'Enable back to top button',
        'bluelte_show_home_page_banner'        => 'Show home page banner',
        'bluelte_banner_head_text'             => 'Banner header text',
        'bluelte_banner_div1_text'             => 'First box text',
        'bluelte_banner_div1_icon'             => 'First box icon',
        'bluelte_banner_div2_text'             => 'Second box text',
        'bluelte_banner_div2_icon'             => 'Second box icon',
        'bluelte_banner_div3_text'             => 'Third box text',
        'bluelte_banner_div3_icon'             => 'Third box icon',
        'bluelte_banner_show_ask_box'          => 'Show ask box in banner',
        'bluelte_banner_closable'              => 'Allow users to close the banner',
        'bluelte_show_collapsible_btns'        => 'Collapse extra buttons into an action button on question page',
        'bluelte_show_breadcrumbs'             => 'Show breadcrumbs at below title (For better looking breadcrumbs , you don\'t have to add it from the Admin/Layout)',
        'bluelte_show_site_stats_above_footer' => 'Show site status above footer',
        'bluelte_show_social_links_at_footer'  => 'Show social links at footer',
        'bluelte_show_copyright_at_footer'     => 'Show copyright at footer',
        'bluelte_copyright_text'               => 'Copyright text',
        'bluelte_general_settings_notice'      => '<h3 class="text-center">BlueLTE general settings</h3>',
        'bluelte_homepage_settings_notice'     => '<h3 class="text-center">BlueLTE homepage settings</h3>',
        'bluelte_footer_settings_notice'       => '<h3 class="text-center">BlueLTE footer settings</h3>',
        'bluelte_social_settings_notice'       => '<h3 class="text-center">BlueLTE social settings</h3>',
        'bluelte_facebook_url'                 => 'Facebook page url',
        'bluelte_twitter_url'                  => 'Twitter url',
        'bluelte_pinterest_url'                => 'Pinterest url',
        'bluelte_google-plus_url'              => 'Google plus url',
        'bluelte_vk_url'                       => 'VK url',
        'bluelte_email_address'                => 'Email address',
        'bluelte_show_custom_404_page'         => 'Show custom 404 page',
        'bluelte_custom_404_text'              => 'Custom 404 text',
        'bluelte_use_local_font'               => 'Use local font (Google fonts will be loaded if unchecked)',
		
    );

    /*
     Omit PHP closing tag to help avoid accidental output
    */
